### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by dhondta** [dhondta/rpl-attacks#17]
Add more tests so that the coverage can be increased.

**Comment by sonxay** [comment]
hi....dhondta
My name is Sonxay , I am PhD student in VietNam.
first of all , i would like to say Thanks for your research RPL attacks
after i read your paper..could i have some question to ask you please.

file serial.log : it likes got the problem
I would like to improve your research : like i want to simulation more like: throughput , end to end delay and Packet delivery Ratio ....How can I do?
Please help me
hope i can get your answer as soon as
thanks
regard
Sonxay
