### ISSUE TITLE
can a node receive its own DIS and transmit DIO after resetting its trickle timer ??

### ISSUE THREAD

**Issue by abhiverma866** [dhondta/rpl-attacks#42]
Can a node receive its own DIS and transmit DIO by resetting its trickle timer ??

```
298514726 ID:7 RPL: Received a DIS from fe80::c30c:0:0:7
298517450 ID:7 RPL: Multicast DIS => reset DIO timer
298639076 ID:7 RPL: Received a DIS from fe80::c30c:0:0:7
298641770 ID:7 RPL: Multicast DIS => reset DIO timer
298891390 ID:7 RPL: Received a DIS from fe80::c30c:0:0:7
298894084 ID:7 RPL: Multicast DIS => reset DIO timer
298934122 ID:7 RPL: Received a DIS from fe80::c30c:0:0:7
298936816 ID:7 RPL: Multicast DIS => reset DIO timer
299139640 ID:7 RPL: Received a DIS from fe80::c30c:0:0:7
299142334 ID:7 RPL: Multicast DIS => reset DIO timer
299262999 ID:7 RPL: Sending a DIS to ff02::1a
299265944 ID:7 RPL: Sending a DIS to ff02::1a
299268890 ID:7 RPL: Sending a DIS to ff02::1a
299271835 ID:7 RPL: Sending a DIS to ff02::1a
299274780 ID:7 RPL: Sending a DIS to ff02::1a
299277763 ID:7 RPL: Sending a DIS to ff02::1a
299280709 ID:7 RPL: Sending a DIS to ff02::1a
299283692 ID:7 RPL: Sending a DIS to ff02::1a
299286637 ID:7 RPL: Sending a DIS to ff02::1a
299289583 ID:7 RPL: Sending a DIS to ff02::1a
299763754 ID:7 RPL: Received a DIS from fe80::c30c:0:0:7      <===
299766448 ID:7 RPL: Multicast DIS => reset DIO timer
299888175 ID:7 RPL: Sending prefix info in DIO for aaaa::
299891343 ID:7 RPL: Sending a multicast-DIO with rank 512
```

**Comment by dhondta** [comment]
Hi @abhiverma866 ,
Your question is a bit hard to answer without a bit more context. I see that you already posted the question [on the repo of Contiki](https://github.com/contiki-os/contiki/issues/2563), so your issue may be independent from the *RPL Attacks Framework*. Could you please answer these questions ?

- Did you get this trace in the `rpl.log` file of an experiment with *RPL Attacks Framework* ?
- Did you customize the simulation `.csc` file ?
- Did you customize Contiki's `core.net.rpl` library ?
- If so, what are your customizations ?

**Note**: In any of the simulations I tried with my framework, I never got a mote to receive a DIS from itself. This may mean you changed something that implies a clash in motes' names or something like that. Please note that I currently don't have time enough to dive deeper into Contiki's sources to figure out, at the C code level, why it behaves like in your trace.
