### ISSUE TITLE
Questions about Creating new building blocks 

### ISSUE THREAD

**Issue by faithphd** [dhondta/rpl-attacks#47]
hi @dhondta I want to implement increased-rank attack and dag inconsistency.
my building block is listed below and I want to ask two questions.

1. Is my building block true for dag-inconsistency and increased-rank? (in my experiments, I could not see too much change in power consumption)
if this building blocks false, what do I need to do in order to implement these attacks?

2. In my simulations, I want to locate malicious mote as a leaf node (as a child of other motes, not as a child of root node), but in all of my simulations malicious mote became a child node of root node and I want to change the location of malicious mote in order to increase the distance(hop count) between malicious mote and root node. can I do it? if I can, In order to do that which parameter do I need to change?

I have changed `min_distance_between_motes` parameter, but I couldn't change the distance between the root and malicious mote and I could not locate malicious mote as a leaf node.

```python
{
  "dag-inconsistency": {
    "RPL_HDR_OPT_DOWN": 1,
    "RPL_HDR_OPT_RANK_ERR": 1
  },
  "increased-rank": {
    "RPL_CONF_MIN_HOPRANKINC": 512,
    "rpl-private.h": [
      ["#define RPL_MAX_RANKINC (7 * RPL_MIN_HOPRANKINC)", "#define RPL_MAX_RANKINC (35 * RPL_MIN_HOPRANKINC)]
    ]
  }
}
```

THANK YOU

**Comment by dhondta** [comment]
Hi @faithphd 
Thank you for submitting your issue.

Your first question requires to look further at the code of ContikiRPL, but I can already answer your second question.

Your simulation is created using a topology generation function and has its parameters contained in the **CSC file** in your experiment folder, meaning that you can edit the position of the malicious mote manually (but this is not that user-friendly). **From the framework console**, you can also edit your simulation by using the **`cooja` command**, which is a simple shortcut to Cooja. You can then close Cooja, return to the framework console and re-run your simulation to get your new report.
