### ISSUE TITLE
Experiment time can not be set  long

### ISSUE THREAD

**Issue by chanseng** [dhondta/rpl-attacks#48]
Dear all,
When I set duration to 1200 sec（or longer)  (The default is 120 sec) in the experiment json file,The experiment will go to half and then no response (usually the without-malicious pcap file is recorded to about 11M).
Has anyone solved this problem? 
Any help is much appreciated.

**Comment by dhondta** [comment]
Hi @chanseng 
Thank you for posting this issue.
I never tried with such a long experiment time but I guess it could be something related to the Cooja tool itself. Therefore, I think this question should be asked in the issues of the repository of [Contiki OS](https://github.com/contiki-os/contiki).

**Comment by chanseng** [comment]
HI@dhondta
Thank you for replying my question.
I tried to increase the jvm of the cooja,and it worked for 800sec.Maybe 1200sec need more jvm :-).

**Comment by dhondta** [comment]
Hi @chanseng 
Thank you very much for this information !
