### ISSUE TITLE
Could not find any downloads that satisfy the requirement cffi

### ISSUE THREAD

**Issue by sahel-vafa** [dhondta/rpl-attacks#50]
Hi,
I run the below commands to run rpl-attacks on Contiki 3.0.
$ git clone https://github.com/dhondta/rpl-attacks.git
sudo apt-get install gfortran libopenblas-dev liblapack-dev $ sudo apt-get install build-essential python-dev libffi-dev libssl-dev $ sudo apt-get install python-numpy python-scipy $ sudo apt-get install libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev $ sudo apt-get install imagemagick libcairo2-dev libffi-dev
sudo apt-get install python-pip
 $  sudo pip install -r requirements.txt
But after the "user@instant-contiki:~/rpl-attacks$ sudo pip install -r requirements.txt
" command I deal with bellow error 
" Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement cffi (from -r requirements.txt (line 1))
Cleaning up...
No distributions at all found for cffi (from -r requirements.txt (line 1))
Storing debug log for failure in /home/user/.pip/pip.log
" 
please help me to fix it. 
I would appreciate you in advance.

**Comment by SalalAmjad** [comment]
Hi Sahel Vafa,
I have solved the same problem before so for you to do the same you just simply need to copy the error and paste it on google and click the link of stackoverflow website and follow the directions provided in that website.
