### ISSUE TITLE
Error during simulation: TypeError Cannot set property "resetViewport" of null

### ISSUE THREAD

**Issue by deGhost** [dhondta/rpl-attacks#53]
Hello,
When using the commands specified in the presentation under the doc folder:
**make test
cooja test (this already launches cooja simulator)
run test (opens a new cooja window)**
Nothing starts, so I started the simulation manually: simulation->start simulation. After exactly time 00.02.801, the script error message is displayed:
![issue](https://user-images.githubusercontent.com/28934708/84653472-c30bfd80-af0d-11ea-8c70-c27eb65c5343.png)

I really need to use the framework and I've tried many things but it's not working. Also, I thought I should add this here when I use the command" "demo" the console is stuck at PROCESSING EXPERIMENT of blackhole-attack
![demo](https://user-images.githubusercontent.com/28934708/84653608-08302f80-af0e-11ea-98bd-9be613fefaec.png)

My SYSTEM specifications I'm using: 
Contiki 3.0 with ubuntu 16.04
Python 3.5
Openjdk 8
Hope to get some help as soon as possible, thank you!

**Comment by dhondta** [comment]
Hi @deGhost 

Thanks for reporting.

For the demo, please beware that it may take a while ; simulations are by default set to a duration of 300s, approximately speed up to ~120s. Did you wait long enough for the run to complete ?

Also, I provide a Vagrant box (sorry, it's huge, with an Ubuntu Desktop of ~4GB) but it is far more convenient for avoiding such errors. This way, you work with the exact same version as I do. When I see the error above, '`Cannot set property "resetViewport" of null`', this may come from various issues, namely if you use a different version of Cooja. This may mean you have a different version of Contiki. I suggest you to `vagrant up` to get the appliance with the tested project on it.

Please let me know if it solves your issue.

**Comment by deGhost** [comment]
@dhondta Thanks for taking the time to reply.

I did wait for more than 30 minutes to allow it to finish the demo but nothing happens.

I fixed the windows10 issue that was preventing me from using vagrant( adding the path to PowerShell to windows global variables), now it works!

Thank you very much for allowing us to use the framework

If I had more time I would dig into the cause of this error (concerning the manual installation) sorry!
