### ISSUE TITLE
explication type of wsn gen algorithm in simulation.conf

### ISSUE THREAD

**Issue by jacobien23** [dhondta/rpl-attacks#57]
i found type of wsn gen algo is quadrants. But i didn't find it in contiki 2.7 or in cooja simulator. Can you give me some information about the different type of wsn gen algo. Thank ou very much.

**Comment by dhondta** [comment]
Hi @yakoubi5103 
You won't find any WSN generation algorithm trace in the Contiki project, as far as I know. This is handled in [this source file](https://github.com/dhondta/rpl-attacks/blob/master/core/common/wsngenerator.py), it generates the positions of the motes in `simulation.csc` to be used in Cooja.
