### ISSUE TITLE
the parameters of performance

### ISSUE THREAD

**Issue by jacobien23** [dhondta/rpl-attacks#58]
Good morning,
I want know how i can extract the parameters of performance like pdr, delay, energy consumption in the plateform rpl-attacks.

**Comment by dhondta** [comment]
Hi @yakoubi5103 
When you make an experiment, it creates a folder in your *Experiments* folder with a structure as follows : 

```
EXPERIMENTS_FOLDER
  +-- EXPERIMENT_NAME
        +-- with-malicious
              +-- data
              +-- motes
                    +-- [compiled motes]
              +-- results
              +-- COOJA.log
              +-- Makefile
              +-- script.js
              +-- simulation.csc
        +-- without-malicious
              +-- [same as for with-malicious]
        +-- report.md
        +-- simulation.conf
```

When the experiment is run, it creates files in the `data` and `results` folders and generates a PDF report based on the Markdown template in the root folder of the experiment. The content of `data` consists of a PCAP and some logs and `results` holds a few generated charts.

As an answer to your question, your subfolder of interest is `EXPERIMENTS_FOLDER/EXPERIMENT_NAME/[with|without]-malicious/data`, which holds the following files : 

```
data
  +-- output.pcap
  +-- powertracker.log
  +-- relationships.log
  +-- rpl.log
  +-- serial.log
```

As you may guess, `powertracker.log` contains energy consumption data while other logs contain various information. You should find your desired data in these files. Afterwards, you will have to parse it (what you can see in `report.pdf` once generated is parsed using [this file](https://github.com/dhondta/rpl-attacks/blob/master/core/utils/parser.py)).

**Comment by jacobien23** [comment]
thank you very much. this information is very helpful😊
