### ISSUE TITLE
simulating on Contiki-OS Cooja

### ISSUE THREAD

**Issue by soeun727** [dhondta/rpl-attacks#61]
hi, I want to simulate your code on Contiki-OS.
Where do I have to locate rpl-attacks code repository? Do I have to locate at Contiki folder where I install contiki?
Please give me answer. Thank you.

**Comment by dhondta** [comment]
You can `git clone` Contiki OS and RPL Attacks Framework in your home folder.
NB : I suggest you use the Vagrant box...
