### ISSUE TITLE
new help please

### ISSUE THREAD

**Issue by Mazin18** [dhondta/rpl-attacks#67]
I tried setting up the frame using instantcontiki 2.7 after sudo pip3 install -r requirements.txt.
Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/cryptography/setup.py", line 14, in <module>

    from setuptools_rust import RustExtension

ImportError: No module named 'setuptools_rust'

I just need to know how to activate the power tracker

**Comment by dhondta** [comment]
As advised on the README, please use the Vagrant box instead of Instant Contiki.
