### ISSUE TITLE
"unable to fetch index base URL https://pypi.python.org/simple/"

### ISSUE THREAD

**Issue by grant1888** [dhondta/rpl-attacks#68]
Hi,

When trying to use "pip install -r requirements.txt" an error appears stating:

"unable to fetch index base URL https://pypi.python.org/simple/"

rpl-attacks$ sudo apt-get install python-pip python-numpy python-scipy

and

rpl-attacks$ sudo apt-get install python3-pip python3-numpy python3-scipy

both work fine.

However, the error occurs when entering:

sudo pip (or pip3) install -r requirements.txt 

(A screenshot of me trying to install cffi on its own and trying to install requirements.txt)

![cffi not installing2](https://user-images.githubusercontent.com/96195444/146224571-8d0596c2-8f99-4fd8-9c10-cd20cf60e6fb.JPG)

**Comment by dhondta** [comment]
Hi @grant1888  !
I advise you to use the provided Vagrant box. I don't have time to troubleshoot the installation of the dependencies on Instant Contiki.
