### ISSUE TITLE
Contiki/Platform issue on colab

### ISSUE THREAD

**Issue by tp4069** [dhondta/rpl-attacks#69]
Hi Sir,

I'm running this program on windows. I got the following error.

![3](https://user-images.githubusercontent.com/88485915/155127235-c917b980-dab2-44ae-84f1-9a168d9cc354.png)
Whether contiki / cooja is possible to install in windows. 

Kindly expecting your reply sir

**Comment by dhondta** [comment]
Hi @tp4069 
This framework is not made to function on Windows. There is even a Vagrant box with preinstalled components.
In the error you get, I see it mentions `/root/contiki/platform` does not exist, meaning Contiki-OS is not installed. This is logical as you use a pre-built online environment that has not this by default. So, unless you find a way to install it on Colab, you won't manage to use RPL Attacks.
